#!/usr/bin/env python3
"""Append Batch Two Val 1 (8 entries) to giants.json and cross-link related."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MASTER = ROOT / "src/data/giants.json"

ENTRIES = [
  {
    "id": "humbaba",
    "slug": "humbaba",
    "name": "Humbaba",
    "alsoKnownAs": ["Huwawa", "Humbaba", "Huwawa of the Cedar Forest"],
    "culture": "Sumerian, Akkadian, later Hurrian and Hittite",
    "region": "Mesopotamia, the Cedar Forest",
    "type": "individual",
    "freeEntry": False,
    "height": None,
    "shortDescription": "The oldest giant in this catalogue by two thousand years. He was not attacking anyone. He was guarding a forest, and two men came to cut it down.",
    "fullDescription": "Huwawa in Sumerian, Humbaba in Akkadian, with the oldest recorded form attested at Mari and Tell Harmal. The origin and meaning of the name are unknown, which is itself a measure of how far back this goes.",
    "mysteryNote": "Mercy was offered once. The sack was heavier than the trees.",
    "related": ["polyphemus", "talos", "tepegoz"],
    "coordinates": [33.9, 35.8],
    "tags": ["mesopotamia", "gilgamesh", "guardian", "oldest"],
    "sources": [
      "The Epic of Gilgamesh in its Old Babylonian and Standard Babylonian versions",
      "the earlier Sumerian Bilgames compositions",
      "Hurrian and Hittite adaptations",
      "Andrew George's edition of the epic",
      "surviving combat scenes and apotropaic clay heads",
    ],
    "image": "/images/giants/humbaba.jpg",
    "imageAlt": "Humbaba, guardian of the Cedar Forest",
    "motifs": ["guardian", "outwitted", "real-site-attached"],
    "sections": {
      "story": "Enlil set him over the Cedar Forest, the dwelling of the gods, and made him a terror to human beings so that no one would enter it. He did the job. His hearing covered the whole forest, so that nothing moved in it without his knowing. His look was described as death, his roar as a flood, his breath as fire.\n\nHis face was drawn as a single continuous coiling line, like the coiled entrails of an animal, and Mesopotamian diviners read omens from exactly such coils. Clay heads of him have been found, made to be hung up for protection. The face that frightened people was also used to keep worse things away.\n\nGilgamesh and Enkidu went into the forest to kill him. While Gilgamesh held his attention, the men they had brought were felling the cedars behind him. Gilgamesh came at him from behind, moved as if to embrace him, and struck. Humbaba, beaten, asked for mercy. Gilgamesh was inclined to give it. Enkidu argued him out of it, and the head went into a leather sack.\n\nThen the part that is easy to miss. Enlil, when the head was brought to him, was not pleased. He took Humbaba's terrors and gave them away: the first to the fields, the second to the rivers, the third to the reed beds. Mercy was offered once. The sack was heavier than the trees.\n\nHe is the oldest thing in this catalogue and he does not fit its usual shape. Nearly every other entry is either a monster that had to be killed or an ancestor who was here first. Humbaba is a park ranger.",
      "origins": "The Epic of Gilgamesh preserves him in Old Babylonian and Standard Babylonian versions. Earlier Sumerian Bilgames compositions stand behind those, and Hurrian and Hittite adaptations carry the same forest guardian into those languages. The oldest recorded form of the name is attested at Mari and Tell Harmal. Andrew George's edition is the working English text of the epic. Surviving combat scenes and apotropaic clay heads show the coiled-entrails face used as a protective image as well as a terror. A tablet recovered relatively recently gives a notably more sympathetic account of him. That tablet belongs to the same epic tradition, not to a modern rewriting.",
      "disputed": "What the story is about. A tablet recovered relatively recently gives a notably more sympathetic account of Humbaba, and modern readings have moved a long way from the monster-slaying frame. In these, the Cedar Forest is a living place with a rightful keeper, the expedition is a logging operation with a hero attached, and Enlil's fury at the end is the point rather than an epilogue.\n\nWhere the forest was is also debated across the textual traditions. Lebanon, the Amanus, and a purely mythic geography all have defenders, and the poems do not settle the map.",
    },
    "fate": "Beheaded after asking for mercy. Enlil was not pleased.",
    "handling": {
      "publishable": True,
      "living": "As of the 2020s Humbaba belongs to no living faith or custodial community. Sumerian and Akkadian religion have no continuous practising body with authority over the Gilgamesh cycle. He survives as ancient literature, museum objects and scholarly edition, all long in the public domain.",
      "distortions": "The common flattening is treating him as a generic monster Gilgamesh needed to kill, erasing that he was set over the forest by Enlil, that he asked for mercy, and that Enlil was angry when the head arrived. A second flattening gives him a generic ogre face instead of the coiled-entrails mask attested on clay heads.",
      "take": "The forest, the coiled face, the logging behind his back, the refused mercy, and Enlil dispersing the terrors into fields, rivers and reed beds are all in the epic and free to use. Do not present the expedition as a simple monster hunt. Keep the later sympathetic tablet visible as a real disagreement in the sources, not as a modern preference.",
      "cite": "Credit the Epic of Gilgamesh in Old Babylonian and Standard Babylonian, the Sumerian Bilgames compositions, Hurrian and Hittite adaptations, and Andrew George's edition, with the surviving clay heads for the face.",
    },
  },
  {
    "id": "tepegoz",
    "slug": "tepegoz",
    "name": "Tepegöz",
    "alsoKnownAs": ["Tepe Göz"],
    "culture": "Oghuz Turkic",
    "region": "Central Asia and Anatolia",
    "type": "individual",
    "freeEntry": False,
    "height": None,
    "shortDescription": "A one-eyed man-eater, blinded in his cave by a young man who tricked him. When a German scholar read the manuscript in 1815, he concluded that Homer had got the story from the East.",
    "fullDescription": "Tepegöz appears in the eighth of the twelve tales of the Book of Dede Korkut, the great epic cycle of the Oghuz Turks. The tale is named for his killer: the story of Basat, who killed Tepegöz.",
    "mysteryNote": "The Dresden manuscript still will not choose a first cave.",
    "related": ["polyphemus", "balor", "katallani"],
    "coordinates": [39.5, 41.0],
    "tags": ["turkic", "oghuz", "one-eye", "dede-korkut", "atu-1137"],
    "sources": [
      "Book of Dede Korkut, Dresden manuscript",
      "H. F. von Diez, Denkwürdigkeiten von Asien, 1815",
      "O. Hackman, 1904",
      "D. Page, 1955",
      "C. S. Mundy, 1956",
      "J. A. Conrad, Fabula 40, 1999",
      "J. d'Huy, 2013",
      "the Sümer, Uysal and Walker translation",
    ],
    "image": "/images/giants/tepegoz.jpg",
    "imageAlt": "Tepegöz, one-eyed giant of the Book of Dede Korkut",
    "motifs": ["one-eye", "outwitted", "cannibal"],
    "sections": {
      "story": "He is born of an illicit union and grows into a plague on the Oghuz people, a one-eyed giant who eats them. Basat confronts him in his cave and blinds him. The shape of the episode is the shape everyone recognises: a hero, a cave, a monster with a single eye, and a blinding.\n\nThe Book of Dede Korkut carries substantial traces of the shamanic belief the Oghuz held before Islam, particularly a persistent respect for the spirits of earth and water as the basis of a workable relationship between people and the natural world. Read that way, Tepegöz is not simply a monster. He is what arrives when that relationship breaks.",
      "origins": "Tepegöz appears in the eighth of the twelve tales of the Book of Dede Korkut. The working witness for the cyclops episode is the Dresden manuscript, which H. F. von Diez found in the royal library in 1815 and published in Denkwürdigkeiten von Asien under a title that translates as The Newly Discovered Oghuz Cyclops. The Sümer, Uysal and Walker translation is the English text most often cited. Oskar Hackman in 1904 collected over a hundred folktales of a one-eyed man-eating giant. The tale type is ATU 1137, the blinded ogre. D. Page (1955), C. S. Mundy (1956), J. A. Conrad in Fabula 40 (1999) and J. d'Huy (2013) are the later stations of that argument.",
      "disputed": "Whether this story or Homer's came first, and whether either borrowed from the other.\n\nIn 1815 H. F. von Diez found a manuscript of the Book of Dede Korkut in the royal library at Dresden. His proposal was that Homer had taken Polyphemus from the East, possibly from oral traditions circulating among the ancient Oghuz.\n\nBy 1904 Oskar Hackman had collected over a hundred folktales of a one-eyed man-eating giant from peoples around the world. The tale has a classification: ATU 1137, the blinded ogre. In 1955 D. Page argued the Homeric episode was derived from earlier folk variants. In 1956 C. S. Mundy argued the reverse. In 2013 Julien d'Huy published a phylogenetic reconstruction of the tale, applying methods borrowed from evolutionary biology to its variants, and argued for a prehistoric origin.\n\nTwo centuries in, there is still no settled answer.",
    },
    "fate": "Blinded in his cave by Basat.",
    "handling": {
      "publishable": True,
      "living": "The Book of Dede Korkut is a medieval Turkic epic still read as cultural heritage in Turkey, Azerbaijan and among Oghuz-descended peoples. It is a published literary cycle, not a restricted ritual text, and the Dresden manuscript has been in scholarly circulation since 1815.",
      "distortions": "The common flattening is treating Tepegöz as a copy of Polyphemus, or Polyphemus as a copy of Tepegöz, when the sources do not settle direction. A second flattening strips the Oghuz shamanic frame (earth and water spirits) and leaves only a generic cyclops.",
      "take": "The cave, the single eye, the blinding, and Basat as the killer are in the Dede Korkut tale and free to use. Present the Homer question as open. Do not assert that Homer borrowed from the Oghuz, or the reverse, as settled fact.",
      "cite": "Credit the Book of Dede Korkut (Dresden manuscript), von Diez 1815, and the Sümer, Uysal and Walker translation, with Hackman, Page, Mundy, Conrad and d'Huy for the ATU 1137 debate.",
    },
  },
  {
    "id": "pangu",
    "slug": "pangu",
    "name": "Pangu",
    "alsoKnownAs": ["P'an-ku"],
    "culture": "Chinese",
    "region": "China",
    "type": "primordial",
    "freeEntry": False,
    "height": "Grew for 18,000 years",
    "shortDescription": "He was not killed. He held the sky up for eighteen thousand years until it stayed there on its own, and then he died of it.",
    "fullDescription": "In the beginning there was no shape to anything. Over roughly eighteen thousand years the formlessness gathered into an egg, and inside it the opposed principles of yin and yang came into balance, and Pangu woke.",
    "mysteryNote": "Ymir is killed and used. Pangu works himself to death, and the world forms without anyone else lifting a hand.",
    "related": ["ymir", "kua-fu", "atlas"],
    "coordinates": [31.0, 114.0],
    "tags": ["china", "creation", "cosmic-egg", "daoist"],
    "sources": [
      "Xu Zheng, Sanwu liji and Wu yun li nianji, 3rd century CE",
      "Shuyi ji",
      "Miao, Yao and Buyei ancestral traditions",
    ],
    "image": "/images/giants/pangu.jpg",
    "imageAlt": "Pangu, holding sky from earth",
    "motifs": ["body-cosmogony", "sky-bearer", "shaped-the-land-while-living"],
    "sections": {
      "story": "He split the egg with an axe. The clear part rose and became the sky, the heavy part sank and became the earth, and because the two would drift back together if left alone, Pangu stood between them and pushed. He grew as the gap grew, taller every day for another eighteen thousand years, until the sky was high enough to stay up by itself.\n\nThen he died, and the world came out of his body: his eyes became the sun and the moon, his breath the wind and clouds, his blood the rivers and the seas, his flesh the soil, his bones the mountains and the ores inside them, his hair the plants and the stars, his sweat the rain, and his four limbs the pillars holding up the four corners of the world.\n\nHe is usually pictured covered in thick hair or fur, horned, with the axe. In art he appears alongside creatures that stand for great age and immortality, the tortoise and the crane, and sometimes the dragon and the phoenix.\n\nSet him beside Ymir. Ymir is killed and dismembered by beings who then use his corpse. Pangu is not killed by anyone. He works himself to death holding the sky up, and the world forms out of him afterwards without any intervention at all.",
      "origins": "The earliest written version is by Xu Zheng in the Three Kingdoms period, in the third century CE, in Sanwu liji and Wu yun li nianji. That is late for a creation myth of this importance. Shuyi ji carries later versions. Miao, Yao and Buyei ancestral traditions also hold Pangu, and the Buyei hold him as their ancestor. His name has also been found in a tomb predating the Three Kingdoms, which complicates the tidy version where Xu Zheng is the beginning. The written Chinese layer is public-domain classical literature. The southern ancestral layer is a living claim and is recorded here as such, not as a licence to invent ritual.",
      "disputed": "How old the story is, and whose it was originally.\n\nThe earliest written version is by Xu Zheng in the Three Kingdoms period, in the third century CE, which is late for a creation myth of this importance.\n\nThat lateness has produced a long argument. Some place the myth's origin in the Western Zhou. Some tie it to the ancestral traditions of the Miao and the Yao of southern China, and the Buyei also hold Pangu as their ancestor. Some argue the core idea of dividing heaven from earth reaches back to the Paleolithic in China, citing the layout of a fifth-millennium BCE shaman's burial from the Yangshao culture in Henan.\n\nHis name has also been found in a tomb predating the Three Kingdoms, which complicates the tidy version where Xu Zheng is the beginning.",
    },
    "fate": "Died holding the sky until it stayed. The world formed from his body.",
    "handling": {
      "publishable": True,
      "living": "The Xu Zheng narrative is classical Chinese literature with no custodial priesthood. Miao, Yao and Buyei ancestral traditions also name Pangu. Those are living claims. This entry retells the published Chinese literary version and notes the southern ancestral layer without inventing ritual or treating Pangu as a generic monster.",
      "distortions": "The common flattening is turning Pangu into a slain chaos-giant like Ymir, when the Chinese account has him die of the work of holding the sky, not of murder. A second flattening treats Xu Zheng as the origin of the myth rather than the earliest surviving written version of a disputed older layer.",
      "take": "The egg, the axe, the eighteen thousand years, the body becoming sun, moon, rivers, mountains and pillars, and the contrast with Ymir are in the written tradition and usable. Do not present Xu Zheng as the inventor of the myth. Do not invent Miao, Yao or Buyei ritual around him.",
      "cite": "Credit Xu Zheng, Sanwu liji and Wu yun li nianji, 3rd century CE, and Shuyi ji, and note Miao, Yao and Buyei ancestral traditions as a separate living layer.",
    },
  },
  {
    "id": "ad-thamud",
    "slug": "ad-thamud",
    "name": "Ad, Iram and Thamud",
    "alsoKnownAs": ["Ad", "Thamud", "Iram of the Pillars", "Aad"],
    "culture": "Arabian and Islamic",
    "region": "the Arabian peninsula and southern Jordan",
    "type": "folklore",
    "freeEntry": False,
    "height": None,
    "shortDescription": "The peoples the Qur'an says were destroyed for arrogance. It does not say they were giants. That part was added later, and recently.",
    "fullDescription": "The Ad and the Thamud appear repeatedly in the Qur'an, usually together, as prosperous peoples who ignored the prophets sent to them and were destroyed. The Ad were ended by a violent wind. Iram of the Pillars, associated with them, is described as a city whose like had not been created.",
    "mysteryNote": "The verse cited to prove giant stature concerns a city, not a body.",
    "related": ["nephilim", "tombe-dei-giganti", "surid", "uj-ibn-anaq"],
    "coordinates": [26.79, 37.95],
    "tags": ["arabia", "quran", "misreading", "archaeology"],
    "sources": [
      "Qur'an 89:6-14 and the Ad and Thamud passages generally",
      "Ahmad Al-Jallad, 2025, on the Ad in Wadi Rum",
      "Nabataean archaeology at Hegra",
    ],
    "image": "/images/giants/ad-thamud.jpg",
    "imageAlt": "Rock-cut tombs at Hegra, later read as giant work",
    "motifs": ["pre-people", "bones-as-proof", "grown-in-the-telling"],
    "statusLine": "The giant claim is a later reading, not in the source text.",
    "sections": {
      "story": "The Ad and the Thamud appear repeatedly in the Qur'an, usually together, as prosperous peoples who ignored the prophets sent to them and were destroyed. The Ad were ended by a violent wind. Iram of the Pillars, associated with them, is described as a city whose like had not been created.\n\nThey are also real, or at least the Ad now appear to be. In 2025 the epigraphist Ahmad Al-Jallad presented evidence identifying the Ad as a tribe present around two thousand years ago in the Wadi Rum region of southern Jordan. The Thamud are attested independently in inscriptions and in the classical sources, and the rock-cut architecture credited to them at Hegra survives.",
      "origins": "Qur'an 89:6-14 and the other Ad and Thamud passages are the primary text. They describe destroyed peoples and a city, not giant bodies. Ahmad Al-Jallad in 2025 presented epigraphic evidence identifying the Ad around Wadi Rum in southern Jordan. The Thamud are attested independently in inscriptions and in classical sources. The rock-cut architecture credited to them at Hegra is Nabataean, cut by people of ordinary height. Shaddad, often named as the king who built Iram, has no basis in the Qur'anic text and none in the archaeological record. Canonical hadith do not describe either people as giants.",
      "disputed": "Everything about the giant claim.\n\nThe Qur'an does not describe either people as giants. Neither do the canonical hadith. The verse cited to prove it concerns a city, not a body. The other stock detail, that the Thamud carved their homes out of rock, is straightforwardly true and has nothing to do with size: those are the Nabataean rock-cut tombs at Hegra, cut by people of ordinary height.\n\nThe giant version is a modern popular reading, and it circulates as a genre rather than as a tradition, alongside images of the trilithon at Baalbek, the Sardinian tombs already covered in this catalogue, and photographs of giant skeletons that are known composites. Where it appears, it appears together with the same claims about suppressed archaeology that attach to the Romanian, Paiute and British material.\n\nWhat the Islamic tradition does say about giant stature is different and runs the opposite way. According to hadith, Adam was created sixty cubits tall, and human beings have been diminishing ever since. That is not a claim about a lost race of giants. It is a claim that we are the shrunken ones.",
    },
    "fate": "Destroyed in the Qur'an for arrogance. The giant reading is later.",
    "handling": {
      "publishable": True,
      "living": "Islam is a living religion. This entry is not a retelling of ritual. It is a record of what the Qur'an actually says about Ad and Thamud, what archaeology has found at Hegra and Wadi Rum, and how a modern giant reading was laid over that. Treat the scripture as scripture. Do not invent giant midrash.",
      "distortions": "The giant claim is the distortion. It is not in the Qur'an or the canonical hadith. Popular posts pair Hegra and Baalbek with composite skeleton photographs and a suppressed-archaeology story that this catalogue already rejects elsewhere.",
      "take": "Quote the destruction for arrogance, Al-Jallad on the Ad, and Hegra as Nabataean work of ordinary height. Do not illustrate or narrate Ad and Thamud as a race of giants. The growth in the telling is the point of the entry.",
      "cite": "Qur'an 89:6-14 and the Ad and Thamud passages, Ahmad Al-Jallad 2025 on Wadi Rum, and Nabataean archaeology at Hegra.",
    },
  },
  {
    "id": "guanche-giants",
    "slug": "guanche-giants",
    "name": "The Giants of the Canaries",
    "alsoKnownAs": ["Guanches", "the giants of Tenerife"],
    "culture": "European accounts of the Guanches",
    "region": "Canary Islands",
    "type": "folklore",
    "freeEntry": False,
    "height": "claimed up to fourteen feet; measured 1.75 to 1.82 metres",
    "shortDescription": "Four chroniclers described the same people in the same century. One called them short. One called them tall. One called them of medium height. Two said they were fourteen feet.",
    "fullDescription": "The Guanches were the indigenous people of the Canary Islands, and they were Amazigh, from the Berber peoples of North Africa. Archaeology and ancient DNA both confirm it, and there is evidence of habitation on Tenerife from the sixth century BCE.",
    "mysteryNote": "Nobody had to wait for the truth to arrive. It was there the whole time, sitting next to the falsehood, and the falsehood travelled better.",
    "related": ["patagonian-giants", "si-te-cah", "ad-thamud"],
    "coordinates": [28.27, -16.64],
    "tags": ["canaries", "guanche", "chronicles", "conquest", "amazigh"],
    "sources": [
      "Le Canarien, 15th century",
      "Alonso de Palencia",
      "Leonardo Torriani",
      "Alonso de Espinosa",
      "Juan de Abreu Galindo",
      "José Viera y Clavijo",
      "skeletal series held in Canarian museums",
      "recent ancient-DNA work on 46 Guanche genomes",
    ],
    "image": "/images/giants/guanche-giants.jpg",
    "imageAlt": "Cave dwellings in Canary Island tuff, empty of giants",
    "motifs": ["bones-as-proof", "pre-people", "grown-in-the-telling", "colonial-distortion"],
    "statusLine": "Claimed in chronicles, contradicted by measurement.",
    "sections": {
      "story": "They lived in caves cut into volcanic tuff and in stone huts, herded goats and sheep, terraced the slopes for cereals, mummified their dead, and organised themselves into chieftaincies. On Tenerife each was ruled by a mencey.\n\nBetween 1402 and 1496 the Crown of Castile took the islands. The Guanches were absorbed, and what survives of them now is skeletal remains, some remarkably preserved mummies, a few hundred recorded words of a lost language, archaeological sites, festivals, place-names, and a detectable proportion of indigenous ancestry in the modern Canarian population.\n\nThe chroniclers who described them could not agree on what they looked like. Le Canarien called the people of Tenerife short and very brave. Alonso de Palencia called them tall men. Abreu Galindo said they were of medium height. Torriani and Espinosa described giants of up to fourteen feet, which is close to four metres.\n\nThese are contemporaries, writing in the same period, about the same population.\n\nThen somebody measured. Skeletal analysis puts Guanche men between 1.75 and 1.82 metres, with the men of Fuerteventura the tallest. That is genuinely tall for fifteenth-century Europeans to encounter, and it is not remotely fourteen feet. The bones held in the museum at Santa Cruz de Tenerife are notably large and thick, which accounts for the impression of unusual physical power without requiring anything unusual about the height.",
      "origins": "Le Canarien is a fifteenth-century chronicle of the conquest. Alonso de Palencia, Leonardo Torriani, Alonso de Espinosa, Juan de Abreu Galindo and José Viera y Clavijo are the other named witnesses to height, and they do not agree. Skeletal series held in Canarian museums, including Santa Cruz de Tenerife, are the measurement. Recent ancient-DNA work on forty-six Guanche genomes identified them as North African, closest to Amazigh peoples of the mainland. Habitation on Tenerife is attested from the sixth century BCE. Read this entry beside the Patagonian Giants: both are European accounts of real indigenous people, inflated in the telling and then deflated by measurement.",
      "disputed": "Very little, at this point, and that is what makes the entry useful.\n\nThe origins were argued over for centuries. The Guanches were proposed as Egyptians, because they mummified their dead in a comparable way. As Scandinavians or Carthaginians. And, persistently, as the surviving remnant of Atlantis, an idea that still attaches to the islands.\n\nForty-six ancient genomes have now settled it. The Guanches were North African, and their closest relatives are the Amazigh peoples of the mainland.\n\nRead this entry beside the Patagonian Giants. Both are European accounts of real indigenous people who were taller than the observers, inflated in the telling and then deflated by measurement, and both end with the people themselves destroyed. The difference is that Patagonia took two and a half centuries to collapse. In the Canaries the contradiction is visible inside a single generation of chronicles.",
    },
    "fate": "Absorbed by conquest. The fourteen-foot claim did not survive the bones.",
    "handling": {
      "publishable": True,
      "living": "The Guanche people as a polity were destroyed in the fifteenth-century conquest. Canarian identity and Amazigh-related ancestry continue. This entry is about the chronicles and the measurements, not a licence to invent surviving giant tribes. Treat descendant Canarian communities as living people, not as a lost race.",
      "distortions": "Atlantis, Egyptian mummy-origin, and fourteen-foot giants are the distortions the chronicles and later popular writing attached. The DNA and the skeletons contradict all three. Do not illustrate this entry as a race of giants.",
      "take": "The disagreement among contemporaries, the 1.75 to 1.82 metre series, the forty-six genomes, and the comparison with Patagonia are the usable core. Do not retell the fourteen-foot figures as fact. The falsehood travelling better is the point.",
      "cite": "Le Canarien, Palencia, Torriani, Espinosa, Abreu Galindo, Viera y Clavijo, Canarian museum series, and the published ancient-DNA work on 46 Guanche genomes.",
    },
  },
  {
    "id": "uj-ibn-anaq",
    "slug": "uj-ibn-anaq",
    "name": "Uj ibn Anaq",
    "alsoKnownAs": ["Uj ibn Anaq", "Ogias"],
    "culture": "Islamic tradition, Arabic and Persian",
    "region": "the Near East",
    "type": "individual",
    "freeEntry": False,
    "height": "Knee-deep in the ocean in later tellings",
    "shortDescription": "He is the biblical Og, after five centuries of retelling. By the end he was standing knee-deep in the open ocean, catching whales and holding them up to the sun to cook.",
    "fullDescription": "Uj ibn Anaq is not in the Qur'an and not in the canonical hadith. He comes into Arabic literature out of Jewish folklore and the Hebrew Bible, where he is Og, the Amorite king of Bashan whom Moses defeats at Edrei. This catalogue already holds him under that name.",
    "mysteryNote": "Same king. Two heights. The later one is the picture.",
    "related": ["og-of-bashan", "goliath", "nephilim", "ad-thamud"],
    "coordinates": [32.8, 35.8],
    "tags": ["islamic", "moses", "folklore", "iconography"],
    "sources": [
      "Numbers 21 and Deuteronomy 3",
      "Arabic and Persian folkloric and exegetical literature",
      "the Book of Giants, c. 2nd century BCE, Dead Sea Scrolls",
      "Islamic manuscript painting",
    ],
    "image": "/images/giants/uj-ibn-anaq.jpg",
    "imageAlt": "Uj ibn Anaq, holding a whale toward the sun",
    "motifs": ["grown-in-the-telling", "pre-people"],
    "sections": {
      "story": "He takes his name from his mother, Anaq, held in the tradition to be a daughter of Adam, and the circumstances of his birth are given as incestuous, which marks him as wrong from the outset rather than merely large.\n\nWhat happened to him afterwards is the point of the entry. In the Hebrew text Og is a king with sixty walled cities who loses a battle. In the Arabic and Persian tradition he grows without limit. He fights Moses directly. He wades into the deep ocean, which reaches only to his knees, catches whales in his hands, and lifts them up toward the sun to fry them.\n\nBoth of these became standard subjects for painters, and he is one of the most illustrated giants in Islamic manuscript art.\n\nThis makes Uj the clearest case in the catalogue of a giant who grew in transmission. The catalogue holds him at two points on the same line: as Og, a defeated regional king, and as Uj, a being for whom the sea is shallow.",
      "origins": "Numbers 21 and Deuteronomy 3 are the Hebrew account of Og of Bashan, already in this catalogue. Uj ibn Anaq is not in the Qur'an and not in the canonical hadith. He enters Arabic and Persian folkloric and exegetical literature from that biblical and Jewish folkloric line. The apocryphal Book of Giants, from around the second century BCE and surviving among the Dead Sea Scrolls, follows a giant named Ogias who fights a great dragon. Islamic manuscript painting made the whale and the knee-deep ocean into standard subjects. Read this entry next to Og of Bashan, not instead of him.",
      "disputed": "Where he came from before the Bible. The apocryphal Book of Giants, from around the second century BCE and surviving among the Dead Sea Scrolls, follows a giant named Ogias who fights a great dragon, and Ogias has been identified either with Og himself or with Og's father.\n\nThat text belongs to the Enochic literature, which means it sits directly alongside this catalogue's existing Nephilim material.\n\nThe growth itself is not in dispute. In the Hebrew text Og is a king with sixty walled cities who loses a battle. In the Arabic and Persian tradition he wades an ocean that reaches his knees. Those are two stages of one name, not two independent giants.",
    },
    "fate": "Grown in the telling until the sea reached his knees.",
    "handling": {
      "publishable": True,
      "living": "Islam is a living religion. Uj is folkloric and pictorial, not Qur'anic and not canonical hadith. Retell the manuscript and painting tradition as folklore. Do not present him as scripture.",
      "distortions": "The distortion is the growth: treating the whale-cooking giant as if that were the biblical Og, or treating Og's iron bed as if it already contained the ocean. Keep the two stages labelled.",
      "take": "The mother Anaq, the battle with Moses in later tellings, the ocean and the whale, and the manuscript paintings are the later tradition and usable as such. Cross-link Og of Bashan. Do not collapse the two into one height.",
      "cite": "Numbers 21 and Deuteronomy 3 for Og; Arabic and Persian folkloric and exegetical literature and Islamic manuscript painting for Uj; the Book of Giants for Ogias.",
    },
  },
  {
    "id": "cailleach",
    "slug": "cailleach",
    "name": "The Cailleach",
    "alsoKnownAs": [
      "Cailleach Bhéara",
      "Cailleach Bheur",
      "Caillagh",
      "Digdi",
      "Garavogue",
    ],
    "culture": "Gaelic: Irish, Scottish, Manx",
    "region": "Ireland, Scotland, Isle of Man",
    "type": "folklore",
    "freeEntry": False,
    "height": "leapt between mountains",
    "shortDescription": "The Neolithic passage tombs at Loughcrew are said to be stones that fell out of her apron while she was jumping between the hills.",
    "fullDescription": "The Cailleach is the divine hag of Gaelic tradition, and her name means the veiled one. She is Cailleach Bhéara in Ireland, Cailleach Bheur in Scotland, Caillagh on Man, and she appears under Digdi, Digde, Garavogue and other names besides.",
    "mysteryNote": "Veil, hammer, apron. The hills keep the inventory.",
    "related": ["jentilak", "fomorians", "daidarabotchi", "klek"],
    "coordinates": [53.74, -7.11],
    "tags": ["gaelic", "winter", "landscape", "megalith", "one-eye", "female"],
    "sources": [
      "The Lament of the Old Woman of Beare, Old Irish",
      "Eleanor Hull, Legends and Traditions of the Cailleach Bheara",
      "Donald Alexander Mackenzie, with the caveat that Beira is his coinage",
      "the Irish folklore collections, in which she is among the most heavily attested figures of all",
      "Seán Ó Duinn on the Beara Peninsula as a ritual landscape",
    ],
    "image": "/images/giants/cailleach.jpg",
    "imageAlt": "The Cailleach leaping between hills, stones falling from her creel",
    "motifs": [
      "builder",
      "shaped-the-land-while-living",
      "petrified",
      "one-eye",
      "real-site-attached",
    ],
    "sections": {
      "story": "She is described as immensely old, veiled, one-eyed, with pale or stone-coloured skin, red or rusted teeth, and long white hair. Some accounts hang skulls on her clothing. On Man she could take the shape of a great bird. She carries a hammer for shaping hills and valleys, and she leaps from mountain to mountain.\n\nAnd as she leaps, stones fall out of her apron, or out of the creel on her back, and where they land there are hills, cairns and islands.\n\nThat is not a figure of speech. The tradition names the places.\n\nLoughcrew in County Meath is Slieve na Caillaigh, the Hills of the Hag, and its Neolithic passage tombs, built around 3500 BCE, are said to be stones she dropped while bounding across the hilltops. Carrowmore in Sligo carries a parallel origin story, and one of its tombs is called Cailleach a Bhéara's House. Ailsa Craig in the North Channel is a load she dropped when a passing ship startled her. Boulders scattered across open ground anywhere in Ireland are commonly said to have come out of her apron.\n\nAt the end of her reign she turned to stone. Hag's Head, the southernmost point of the Cliffs of Moher, is said to be her profile, still looking out to sea. On the Beara Peninsula in Kerry a weathered stone is her resting place.\n\nShe is attached to more locations across the Gaelic-speaking world than any other figure in that tradition. Over eight hundred folklore entries record her.",
      "origins": "The Lament of the Old Woman of Beare is an Old Irish poem and one of the named sources for a figure who shares this name. Eleanor Hull's Legends and Traditions of the Cailleach Bheara collected the landscape and hag material. Donald Alexander Mackenzie popularised her as Beira, Queen of Winter, a twentieth-century coinage, not a traditional name. The Irish folklore collections record her among the most heavily attested figures in that corpus. Seán Ó Duinn treats the Beara Peninsula as a ritual landscape. Loughcrew, Carrowmore, Ailsa Craig and Hag's Head are the named sites. This catalogue places Mackenzie's Beira alongside Kalevipoeg: real folk material with a modern authored layer on top.",
      "disputed": "What she is. The sources never reconcile three figures who share the name: the mourning old woman of one of the finest Old Irish poems, a sovereignty hag who makes kings, and a landscape giant who dropped the cairns from her apron. She is a winter deity, a creator, a hag, a goddess and a giantess depending on which account you are reading, and calling her a giant is one framing among several rather than the settled answer.\n\nBeira, Queen of Winter, is a twentieth-century coinage by the folklorist Donald Alexander Mackenzie, not a traditional name. That places her alongside Kalevipoeg and Veli Jože in this catalogue: real folk material with a modern authored layer on top that is routinely mistaken for the tradition itself.",
    },
    "fate": "Turned to stone. Hag's Head still looks out to sea.",
    "handling": {
      "publishable": True,
      "living": "Gaelic folklore is still told, and the Cailleach is among the most collected figures in the Irish folklore archives. She is public folklore rather than a restricted sacred cycle. Mackenzie's Beira is a modern literary overlay and should be labelled as such.",
      "distortions": "The common flattening is treating Beira, Queen of Winter, as the traditional name, and treating the lament, the sovereignty hag and the landscape giantess as one settled being. The sources do not reconcile those three.",
      "take": "The apron, the named sites, the one eye, the hammer, and the turning to stone are in the folklore collections and usable. Keep the three figures under one name unreconciled. Do not present Mackenzie as tradition.",
      "cite": "The Lament of the Old Woman of Beare, Eleanor Hull, the Irish folklore collections, Seán Ó Duinn on Beara, and Mackenzie only with the Beira caveat.",
    },
  },
  {
    "id": "surid",
    "slug": "surid",
    "name": "Surid ibn Salhouk",
    "alsoKnownAs": ["Surid", "Souphis"],
    "culture": "Coptic and Islamic Egypt, medieval",
    "region": "Egypt",
    "type": "folklore",
    "freeEntry": False,
    "height": None,
    "shortDescription": "A king who dreamed the Flood was coming, and built the pyramids to keep knowledge safe from the water. His name is a corruption of the name of the pharaoh who actually built them.",
    "fullDescription": "Surid belongs to medieval Coptic and Islamic Egypt, not to ancient Egypt. He is placed roughly three hundred years before the Flood, and in several tellings he is a giant.",
    "mysteryNote": "Khufu kept his name. The flood-king grew around it.",
    "related": ["xelhua", "ad-thamud", "mouros", "tombe-dei-giganti"],
    "coordinates": [29.98, 31.13],
    "tags": ["egypt", "pyramids", "flood", "knowledge", "antediluvian"],
    "sources": [
      "al-Masudi, d. 967",
      "Ibn Abd al-Hakam",
      "Abu Ma'shar al-Balkhi, Book of Thousands",
      "Ibrahim ibn Wasif Shah",
      "Murtada ibn al-Afif, History of Egypt, before 1237",
      "al-Maqrizi, al-Khitat, 14th century",
      "Sa'id al-Andalusi",
      "Ammianus Marcellinus, 4th century",
    ],
    "image": "/images/giants/surid.jpg",
    "imageAlt": "The Giza pyramids in flood, no giant king",
    "motifs": ["builder", "pre-people", "grown-in-the-telling"],
    "statusLine": "Medieval legend laid over a named builder.",
    "sections": {
      "story": "The story is consistent across the sources. Surid dreamed that the earth would be overturned, submerged by water and then visited by fire. Fearing that knowledge and the arts would be lost, he ordered the pyramids built as repositories: astronomy, medicine, mathematics and engineering inscribed inside them, along with treasures, talismans, idols, and the mummified bodies of his ancestors. He set guardians over them. The workforce is given as a hundred thousand men in rotating shifts over twenty years.\n\nHe is repeatedly identified with Enoch, with the Muslim prophet Idris, and with Hermes Trismegistus, three figures who were themselves already being conflated with each other.\n\nA rival tradition credited the pyramids instead to Shaddad ibn Ad, the legendary king of the Adites and builder of Iram of the Pillars. The Copts rejected that version on a specific and rather good ground: they held that neither the Adites nor the Amalekites had ever managed to invade Egypt, because Egyptian magic had always been sufficient to keep them out.",
      "origins": "The legend belongs to medieval Coptic and Islamic Egypt, not to the Old Kingdom. al-Masudi (d. 967), Ibn Abd al-Hakam, Abu Ma'shar al-Balkhi's Book of Thousands, Ibrahim ibn Wasif Shah, Murtada ibn al-Afif's History of Egypt (before 1237), al-Maqrizi's al-Khitat (14th century) and Sa'id al-Andalusi are the named Arabic witnesses. In the fourth century Ammianus Marcellinus already reported the belief that inscriptions in underground galleries had been made to preserve ancient wisdom against the flood. Athanasius Kircher carried the Arabic pyramid material into European scholarship in the 1600s. The name Surid derives from Souphis, the Greek form of Khufu, who did build the Great Pyramid.",
      "disputed": "The name gives the game away. Surid derives from Souphis, which is the Greek form of Khufu, the pharaoh who did build the Great Pyramid.\n\nThat makes this different from every other megalith legend in the catalogue. In the Basque country, in Galicia, in Sardinia and in Istria, the builders were genuinely forgotten and giants filled an empty space. In Egypt the builder's name survived the whole way through, and the legend grew on top of it anyway, until the pharaoh had become an antediluvian giant who was also Enoch and also Hermes.\n\nThe legend was not new in the Islamic period either. In the fourth century Ammianus Marcellinus already reported the belief that inscriptions in underground galleries had been made to preserve ancient wisdom against the flood.\n\nIts afterlife is the reason it matters now. Athanasius Kircher carried the Arabic pyramid material into European scholarship in the 1600s, and from there the idea of the pyramids as a pre-flood archive of lost knowledge passed into modern pseudo-archaeology, where it remains the single most repeated claim about them.",
    },
    "fate": "The name is Khufu. The legend grew on top of the builder.",
    "handling": {
      "publishable": True,
      "living": "This is medieval Coptic and Islamic literary tradition about the pyramids, not a living ritual claim and not Old Kingdom religion. Treat it as legend laid over a named pharaoh.",
      "distortions": "The distortion is the one the entry exists to name: an antediluvian giant-king archive, still the most repeated modern claim about the pyramids. Kircher is the European pipeline. Do not illustrate a giant building Giza.",
      "take": "The flood-dream, the archive, the hundred thousand men, the Enoch/Idris/Hermes conflation, and the Coptic rejection of Shaddad are in the medieval sources and usable as legend. Keep Khufu visible. Do not present Surid as the historical builder.",
      "cite": "al-Masudi, Ibn Abd al-Hakam, Abu Ma'shar, Murtada ibn al-Afif, al-Maqrizi, Ammianus Marcellinus, and the derivation of Surid from Souphis/Khufu.",
    },
  },
]


def add_related(giant: dict, slug: str) -> None:
    rel = list(giant.get("related") or [])
    if slug not in rel:
        rel.append(slug)
        giant["related"] = rel


def main() -> None:
    data = json.loads(MASTER.read_text())
    existing = {g["slug"] for g in data}
    for e in ENTRIES:
        if e["slug"] in existing:
            raise SystemExit(f"already present: {e['slug']}")
        data.append(e)

    links = {
        "polyphemus": "tepegoz",
        "talos": "humbaba",
        "ymir": "pangu",
        "kua-fu": "pangu",
        "atlas": "pangu",
        "balor": "tepegoz",
        "katallani": "tepegoz",
        "nephilim": "ad-thamud",
        "tombe-dei-giganti": "ad-thamud",
        "og-of-bashan": "uj-ibn-anaq",
        "goliath": "uj-ibn-anaq",
        "patagonian-giants": "guanche-giants",
        "si-te-cah": "guanche-giants",
        "jentilak": "cailleach",
        "fomorians": "cailleach",
        "daidarabotchi": "cailleach",
        "klek": "cailleach",
        "xelhua": "surid",
        "mouros": "surid",
    }
    by = {g["slug"]: g for g in data}
    for src, dst in links.items():
        add_related(by[src], dst)

    MASTER.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
    print("entries", len(data), "added", [e["slug"] for e in ENTRIES])


if __name__ == "__main__":
    main()
